//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furlough.Resources.Services.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furlough.Resources.Services.Mail.RequestCreate", typeof(RequestCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:flex;flex-direction:column;&quot;&gt;&lt;p&gt;Dear {0},&lt;/p&gt;&lt;p&gt;Your new request submitted on {1} was registered in our system.&lt;/p&gt;&lt;br/&gt;We&apos;ll let you know once it&apos;s status changes.&lt;/p&gt;&lt;br/&gt;&lt;br/&gt;&lt;p&gt;Request details:&lt;/p&gt;&lt;i&gt;Request Id: {2}&lt;br/&gt;Type: {3}&lt;br/&gt;Dates: {4}&lt;br/&gt;Total days: {5}&lt;br/&gt;&lt;/i&gt;&lt;/div&gt;&lt;div style=&quot;font-size:0.6rem&quot;&gt;&lt;p&gt;This email was intended for {6}&lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        public static string employeeBody {
            get {
                return ResourceManager.GetString("employeeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request created with ID {0}.
        /// </summary>
        public static string employeeSubject {
            get {
                return ResourceManager.GetString("employeeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:flex;flex-direction:column;&quot;&gt;&lt;p&gt;Dear {0},&lt;/p&gt;&lt;p&gt;{1} has requested {2} total days leave on these dates:&lt;/p&gt;&lt;i&gt;{3}&lt;/i&gt;&lt;/p&gt;&lt;br/&gt;&lt;div&gt;&lt;p&gt;Request details:&lt;/p&gt;&lt;i&gt;Request Id: {4}&lt;br/&gt;Type: {5}&lt;br/&gt;Dates: {3}&lt;br/&gt;Total days: {2}&lt;br/&gt;&lt;/i&gt;&lt;/div&gt;&lt;div&gt;&lt;p&gt;You can make changes to the status of the request once you login to the Vacation Management System.&lt;/p&gt;&lt;/div&gt;&lt;div style=&quot;font-size:0.6rem&quot;&gt;&lt;p&gt;This email was intended for {6}&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string managerBody {
            get {
                return ResourceManager.GetString("managerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request by {0}!.
        /// </summary>
        public static string managerSubject {
            get {
                return ResourceManager.GetString("managerSubject", resourceCulture);
            }
        }
    }
}
