//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furlough.Resources.Services.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestEdit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furlough.Resources.Services.Mail.RequestEdit", typeof(RequestEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;div&gt;Your request that was made on &lt;i&gt;{0}&lt;/i&gt; has been approved!&lt;/div&gt;&lt;div class=&quot;display:flex; flex-direction: column;&quot;&gt;&lt;div&gt;Details&lt;/div&gt;&lt;div&gt;Leave type: &lt;b&gt;{1}&lt;/b&gt;&lt;br/&gt;Dates: &lt;b&gt;{2}&lt;/b&gt;&lt;br/&gt;Total days: &lt;b&gt;{3}&lt;/b&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string requestApproved {
            get {
                return ResourceManager.GetString("requestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;div&gt;Your request that was made on &lt;i&gt;{0}&lt;/i&gt; has been cancelled.&lt;/div&gt;&lt;div class=&quot;display:flex; flex-direction: column;&quot;&gt;&lt;div&gt;Details&lt;/div&gt;&lt;div&gt;Leave type: &lt;b&gt;{1}&lt;/b&gt;&lt;br/&gt;Dates: &lt;b&gt;{2}&lt;/b&gt;&lt;br/&gt;Total days: &lt;b&gt;{3}&lt;/b&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string requestCancelled {
            get {
                return ResourceManager.GetString("requestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;div&gt;Your request that was made on &lt;i&gt;{0}&lt;/i&gt; is set to pending.&lt;/div&gt;&lt;div class=&quot;display:flex; flex-direction: column;&quot;&gt;&lt;div&gt;Details&lt;/div&gt;&lt;div&gt;Leave type: &lt;b&gt;{1}&lt;/b&gt;&lt;br/&gt;Dates: &lt;b&gt;{2}&lt;/b&gt;&lt;br/&gt;Total days: &lt;b&gt;{3}&lt;/b&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string requestPending {
            get {
                return ResourceManager.GetString("requestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;div&gt;Your request that was made on &lt;i&gt;{0}&lt;/i&gt; has unfortunately been rejected.&lt;/div&gt;&lt;div class=&quot;display:flex; flex-direction: column;&quot;&gt;&lt;div&gt;Details&lt;/div&gt;&lt;div&gt;Leave type: &lt;b&gt;{1}&lt;/b&gt;&lt;br/&gt;Dates: &lt;b&gt;{2}&lt;/b&gt;&lt;br/&gt;Total days: &lt;b&gt;{3}&lt;/b&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string requestRejected {
            get {
                return ResourceManager.GetString("requestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0}.
        /// </summary>
        public static string requestSubject {
            get {
                return ResourceManager.GetString("requestSubject", resourceCulture);
            }
        }
    }
}
