//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furlough.Resources.Models.Request {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furlough.Resources.Models.Request.Display", typeof(Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string dates {
            get {
                return ResourceManager.GetString("dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total business days.
        /// </summary>
        public static string daysAmount {
            get {
                return ResourceManager.GetString("daysAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by user.
        /// </summary>
        public static string lubUserId {
            get {
                return ResourceManager.GetString("lubUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update date.
        /// </summary>
        public static string lud {
            get {
                return ResourceManager.GetString("lud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update number.
        /// </summary>
        public static string lun {
            get {
                return ResourceManager.GetString("lun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request by user.
        /// </summary>
        public static string requestedByUserId {
            get {
                return ResourceManager.GetString("requestedByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested on.
        /// </summary>
        public static string requestedOn {
            get {
                return ResourceManager.GetString("requestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status.
        /// </summary>
        public static string requestStatusId {
            get {
                return ResourceManager.GetString("requestStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string requestTypeId {
            get {
                return ResourceManager.GetString("requestTypeId", resourceCulture);
            }
        }
    }
}
